<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HtmlSanitizer" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" />
    <PackageReference Include="Microsoft.Extensions.Localization" />
    <PackageReference Include="Polly.Core" />
    <PackageReference Include="Markdig" />
    <PackageReference Include="mu88.Shared" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\SystemPrompt.txt" />
  </ItemGroup>

</Project>
