name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'
      - name: Restore dependencies
        run: dotnet restore ShopAndEat.sln
      - name: Build
        run: dotnet build --no-restore ShopAndEat.sln
      - name: Test
        run: dotnet test --collect:"XPlat Code Coverage" --no-build --settings Tests/coverlet.runsettings
      - name: Upload code coverage report
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: Tests/TestResults/*/coverage.cobertura.xml
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: mu88/shopandeat:latest
          file: ShopAndEat/Dockerfile
