name: Combined CI / Release

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  shared_ci_cd:
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write

    uses: mu88/common/.github/workflows/ci-cd.yml@8aa4af26d12ca6f08cd017f505b39a7121d2e9c4
    with:
      docker-attest-provenance-and-sbom: true
      docker-publish-project: ShopAndEat/ShopAndEat.csproj
      requires-docker-login: true
      sonar-key: mu88_ShopAndEat
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
