name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'
      - name: Restore dependencies
        run: dotnet restore ShopAndEat.sln
      - name: Build
        run: dotnet build --no-restore ShopAndEat.sln
      - name: Test
        run: dotnet test --no-build --verbosity normal ShopAndEat.sln
      - name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          registry: registry.hub.docker.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Write release version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Build Docker and Push
        run: dotnet publish ShopAndEat/ShopAndEat.csproj --os linux --arch arm64 /t:PublishContainer '-p:ContainerImageTags="${{ env.VERSION }};latest"' -p:ContainerRegistry=registry.hub.docker.com
